// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvmp-DGTnmAQVOzACfN_mbAX5K7hIuqfo',
    appId: '1:951614019398:web:2c7ae0d99353a7f898f747',
    messagingSenderId: '951614019398',
    projectId: 'filegenius-app1',
    authDomain: 'filegenius-app1.firebaseapp.com',
    storageBucket: 'filegenius-app1.firebasestorage.app',
    measurementId: 'G-YS2QFFV26Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmGpNC5emDzio94m0nB7858eaDTm53j9A',
    appId: '1:951614019398:android:721720955ac8c57898f747',
    messagingSenderId: '951614019398',
    projectId: 'filegenius-app1',
    storageBucket: 'filegenius-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXAwWhDQIgzMRuF1neFemN_crYElOP2fY',
    appId: '1:951614019398:ios:042119432abf2c7498f747',
    messagingSenderId: '951614019398',
    projectId: 'filegenius-app1',
    storageBucket: 'filegenius-app1.firebasestorage.app',
    iosClientId: '951614019398-ko2nhf1suvljt47eo21v3gvjknngpi03.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileGenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXAwWhDQIgzMRuF1neFemN_crYElOP2fY',
    appId: '1:951614019398:ios:042119432abf2c7498f747',
    messagingSenderId: '951614019398',
    projectId: 'filegenius-app1',
    storageBucket: 'filegenius-app1.firebasestorage.app',
    iosClientId: '951614019398-ko2nhf1suvljt47eo21v3gvjknngpi03.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileGenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvmp-DGTnmAQVOzACfN_mbAX5K7hIuqfo',
    appId: '1:951614019398:web:7c53c2ffa1a80cd498f747',
    messagingSenderId: '951614019398',
    projectId: 'filegenius-app1',
    authDomain: 'filegenius-app1.firebaseapp.com',
    storageBucket: 'filegenius-app1.firebasestorage.app',
    measurementId: 'G-XJCDTHNNEZ',
  );
}
